name: CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Config env variables
        run: npm run config
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Build prod
        run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
